import type { NextPage, GetServerSidePropsContext, GetServerSideProps } from 'next';
import Head from 'next/head';
import React, { ReactElement, ReactNode } from 'react';
import AuthLayout from '../src/layouts/AuthLayout';
import DashboardContainer from '../src/modules/dashboard/containers/DashboardContainer';
import { withSession } from './_app';

const Dashboard = () => {
    return (
        <div>
            <Head>
                <title>Club Management | Dashboard</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <DashboardContainer />
        </div>
    );
};

Dashboard.getLayout = (page: ReactElement) => {
    return <AuthLayout>{page}</AuthLayout>;
};

export const getServerSideProps = withSession(async (ctx, user) => {
    if (user) {
        return {
            props: {
                user,
            },
        };
    }
    return { redirect: { destination: '/', permanent: false } };
});

export default Dashboard;
