import type { NextPage } from 'next';
import Head from 'next/head';
import React from 'react';
import DashboardContainer from '../src/modules/dashboard/containers/dashboardContainer';

const Home: NextPage = () => {
    return (
        <React.Fragment>
            <Head>
                <title>Club Management | Dashboard</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <DashboardContainer />
        </React.Fragment>
    );
};

export default Home;
