import type { NextPage } from 'next';
import Head from 'next/head';
import React from 'react';
import LoginContainer from '../src/modules/loginSignup/containers/LoginContainer';

const Home: NextPage = () => {
    return (
        <React.Fragment>
            <Head>
                <title>Club Management | Login</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <LoginContainer />
        </React.Fragment>
    );
};

export default Home;
